### ISSUE TITLE
editor functions broke in repeater or flexible content field

### ISSUE THREAD

**Issue by adrien44** [Log1x/acf-move-wp-editor#1]
I just notice that the plugin doesn't work when used inside a flexible content !

All editor options (bold, italic,....) are hidden except for the "add medias button". (add medias button is still functional probably because not inside the same div as basics options) 
And switch between visual editor or brut text is not possible anymore.

From what I can observe it could be link to issues regarding using "append" with elements that already use jquery trigger. (If not set with "live" or "on")

![capture d ecran 2018-02-12 a 17 40 08](https://user-images.githubusercontent.com/4097397/36107944-d74f68ec-101b-11e8-9f44-592b68efc720.png)

**Comment by Log1x** [comment]
It shouldn't be used inside of flexible content. It's only meant to be used once, and is simply moving the content editor for your page or post to say an accordion or a tab for better back-end styling.

**Comment by adrien44** [comment]
Totally agree with you on the logic for the repeater field.

But I use flexible content only to let admin chose 1 layout among severals. Each layout having specific fields.
In this case it should make sense to be able to use WP editor.

**Comment by Log1x** [comment]
For that, I'd recommend hiding the default editor and then perhaps hooking `save_post` to add your content from a custom field.

Example:

```php
add_action('acf/save_post', function ($post_id) {
    $content = get_field('content_example', $post_id);
    if (!empty($content)) {
        wp_update_post([
            'ID' => $post_id,
            'post_content' => $content
        ]);
    }
});
```

**Comment by adrien44** [comment]
Thanks for the feedback. 
That will do the trick for me :)
